export const tags = [
  { id: "all", label: "Все" },
  { id: "web", label: "Веб-разработка" },
  { id: "design", label: "Дизайн" },
  { id: "books", label: "Книги" },
  { id: "gamedev", label: "Разработка игр" },
  { id: "frameworks", label: "Фреймворки" },
  { id: "freelance", label: "Фриланс" },
  { id: "adobe", label: "Adobe" },
  { id: "android", label: "Android" },
  { id: "backend", label: "Backend" },
  { id: "figma", label: "Figma" },
  { id: "frontend", label: "Frontend" },
  { id: "git", label: "Git" },
  { id: "go", label: "Go" },
  { id: "html-css", label: "HTML/CSS" },
  { id: "ios", label: "IOS" },
  { id: "javascript", label: "JavaScript" },
  { id: "product", label: "Product" },
  { id: "python", label: "Python" },
  { id: "react", label: "React" },
  { id: "sql", label: "SQL" },
  { id: "ui-ux", label: "UI/UX" },
];
